alphagov/accessible-autocomplete

- CHANGELOG.md
- examples/styled.css
- examples/styled.html
- src/typeahead.jsx
- Provide `styled.css` as a separate file, which can also be included by other projects.
- Use our own classes for now instead of the jQuery typeahead ones. We will add these back in once we create a proper shim for it.
- Tweak the styling to fix two Safari bugs: a scroll bar appearing where none is necessary, and a weird margin separating the input from the menu.
> Changes to styling

- CHANGELOG.md
- README.md
- src/typeahead.jsx
- src/wrapper.jsx
- test/browser/index.jsx
This allows using the typeahead with an actual HTML form.
> Add ability to specify name attribute

- CHANGELOG.md
- src/typeahead.jsx
- test/browser/index.jsx
This allows VoiceOver users the ability to more easily select from available options.
> Don't close the menu when blurring keyboard on iOS

- src/typeahead.jsx
- test/browser/index.jsx
This was introduced in #5.
Also clean up some unnecessary lines from a few tests.
> Close the menu when the query becomes empty

- examples/styled.css
This was introduced by accident when I refactored the CSS.
> Remove border-radius on iOS in styled version

- CHANGELOG.md
- src/typeahead.jsx
This will prevent selecting the text when arrowing out of the options.
> Select text only when unfocused

- CHANGELOG.md
- examples/styled.html
- src/status.jsx
- src/typeahead.jsx
- src/wrapper.jsx
- test/browser/index.jsx
This:
- Tells the aria region to display text informing the user should type in more characters;
- Doesn't call the `source` until that lower limit is reached.
> Add `minLength` property

- examples/styled.css
- src/typeahead.jsx
Update content and styling for "no options found"
Before:
After:
@tvararu ideally this content would be configurable.
> No options content

- CHANGELOG.md
- README.md
- examples/index.html
- src/typeahead.jsx
- src/wrapper.jsx
- test/browser/index.jsx
Add ability to specify a `defaultValue` to prefill the input.
> Add `defaultValue` property

- CHANGELOG.md
- src/typeahead.jsx
- test/browser/index.jsx
- When user has selected an option with the keyboard, blur will select
- When user has no selected but autoselect is on, blur will select
- Hovering no longer selects, just focuses
- When hovering out of component, focus returns to selected
- Allow enter to submit forms when menu isn't opened
- Hide results when going under minLength
> Multiple fixes

- README.md
There should be a comma between the element and id object fields.
> Fix minor syntax error in README example

- CHANGELOG.md
- README.md
- examples/index.html
- src/typeahead.jsx
- src/wrapper.jsx
- test/browser/index.jsx
This PR adds a `AccessibleTypeahead.enhanceSelectElement` helper function which will:
- Place a typeahead input field adjacent to the specified `<select>`
- Set the typeahead `defaultValue` to the `option[selected]` if any
- Default the typeahead `id` to the `<select>`'s `id`
- Default the typeahead `name` attribute to `''` to prevent it being included in form submissions
- Default the typeahead `source` to a basic one that uses any existing `<option>`s from the `<select>`
- Hide the `<select>` using inline `display: none`
- Set the `<select>`'s id to `${id}-select` to decouple from any `<label>`
- Upon selecting a value in the typeahead, update the original `<select>`
Also includes some README reorg/cleanup.
Closes #25.
> Add `enhanceSelectElement` function and `onSelect` property

- CHANGELOG.md
- README.md
- examples/index.html
- src/typeahead.jsx
- src/wrapper.jsx
- test/browser/index.jsx
- Pass actual selected object into `onSelect`.
- Add `selectOnBlur` property to allow users to disable this behaviour.
> `onSelect` fixes

- accessibility-criteria.md
This describes the necessary behaviours that a typeahead needs to meet to be usable by assistive technologies.
In the future we might want to move these to more prominent documentation, or enhance them with automated tests that verify the outlined behaviours.
> Add accessibility-criteria.md

- CHANGELOG.md
- examples/styled.css
- src/typeahead.jsx
- test/browser/index.jsx
This allows users to continue typing when they are focusing an option.
> Pass through unrecognised keys to input

- CHANGELOG.md
- examples/styled.css
- src/typeahead.jsx
- test/browser/index.jsx
The way hovering previously worked is it would `.focus` the underlying element, which would apply the focus styles.
The reason it was done this way was because the component was built with keyboard in mind before mouse; for keyboard use to work well with assistive technologies, focusing is necessary for the current implementation. When I added mouse support, I made the mouse perform the same action as the keyboard, which is focusing.
This had an added benefit: when using a screenreader like VoiceOver, focusing on suggestions while the user mouses over them would make VoiceOver speak them out, which could be seen as a win for users with enough sight to use the mouse, but that need to rely on a screen reader to actually read words.
However, the side effect to this is when using the …
> Don't focus suggestions when hovering them

- src/typeahead.jsx
- test/browser/index.jsx
This was left over when the code was transitioned to separate the `focused` state from the `selected` state.
> Do not unselect from options when clicking on input

- src/typeahead.jsx
Custom suggestions don't seem to bubble events correctly if you just use the native browser `click` handler on the parent. `touchEnd` does seem to work.
This allows iOS to reliably click on custom suggestions.
> Add touchEnd handler for iOS and touch devices

- CHANGELOG.md
- package.json
At the Home Office we use a sass compiler that reads from a "style" declaration in package.json files of npm installed modules when compiling css.
By adding a "style" declaration we can include this module's css into our built and compiled code more easily.
Before:
```
@import "accessible-typeahead/dist/styled.min.css"
```
After:
```
@import "accessible-typeahead"
```
It's a pretty minor thing, but smoothes the developer experience as no knowledge of the package internal structure is required to implement.
> Add "style" declaration in package.json

- src/typeahead.js
This allows screen reader users to more easily discover it.
> Move aria live region above input

- src/typeahead.js
This prevents JAWS and NVDA from picking it up on initial page load as a possible form element, which they do in spite of the `tabindex="-1"`.
Closes #56.
Tested:
> Only render hint input if there is something to hint

- CHANGELOG.md
- README.md
- src/wrapper.js
- test/functional/wrapper.js
Throw more errors when required arguments are not passed into `accessibleTypeahead` or `enhanceSelectElement`.
Slightly update the README based on feedback from @nickcolley.
> Better errors

- package.json
Trying to compile some sass which includes this module fails because the referenced file in package.json no longer exists. Update the reference to point to the new file.
> Update `style` property in package.json to reflect updated filename

- .travis.yml
- CONTRIBUTING.md
- test/wdio.config.js
This should allow us to do integration testing on PRs from forks.
In addition to this, I've changed the `SAUCE_ENABLED` variable to be a private one on Travis to prevent it from being set to true on fork PRs.
See:
- https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
- dwyl/learn-nightwatch#8
> Make integration tests run on Travis !SAUCE_ENABLED

- CHANGELOG.md
- README.md
- src/wrapper.js
- test/functional/wrapper.js
Allows the common pattern for `<select>` elements in forms to have a default option with no value and a placeholder text to be supported out of the box.
* Uses `defaultValue` only when the `<select>` element has no selected value (i.e. when a null option is selected)
* Filters out any null-valued options from the option list used to populate the `source` array for autocomplete
* Adds a flag to optionally not apply the above filter
* Refactors the `enhanceSelectElement` tests to reduce repetition of setup code
* Removes some of the test scope for `can enhance a select element` on the basis that it's too vague to be helpful. Assertions have been split out into more specific tests
> Add a null option support for `enhanceSelectElement`

- package.json
`npm build` is not equivalent to `npm run build` - we need the latter here.
> Fix `version` script to compile assets

- README.md
- src/autocomplete.js
- webpack.config.babel.js
I naively changed this from an `onInput` to an `onChange` when I saw that it "worked fine" in Preact. However, it wasn't working in reality; the `pollInputElement` handler was making it look like it.
We can't use `onInput` in both Preact and React because it fails in React on IE10.
Also removed the confusing / unused default for the `id` prop.
> Fix onChange/onInput event handler

- scripts/check-staged.js
The prepush script will fail when `git diff dist/` returns a really long output which causes Node to throw `stdout maxBuffer exceeded`.
`git diff --name-only` outputs only the changed filenames which is much shorter.
Also display the actual stack trace in the event of an unexpected error.
> Update prepush script to only look at file names

- package-lock.json
- package.json
- yarn.lock
`webpack-dev-server` has a transitive dependency on `webpack-dev-middleware@^1.0.11`, but `1.11.0` breaks our development server for reasons unknown. (Might be this: https://github.com/webpack/webpack-dev-middleware/pull/187)
`1.10.2` is a version that works, and strictly specifying it in `package.json` will get both yarn and npm to respect it when resolving dependencies.
Fixes #172.
> Add explicit dependency on webpack-dev-middleware

- test/wdio.config.js
Part fix for failing Travis build reported in
https://github.com/alphagov/accessible-autocomplete/issues/253
We hadn't tied SauceLabs to a version of Firefox. We haven't done
active development on the repo for a bit so it looks like the latest FF is not
compatible.
Tested as part of this PR: https://github.com/alphagov/accessible-autocomplete/pull/254
I wonder if we should specify Chrome version as well?
> Pin Firefox version for SauceLabs tests

- webpack.config.babel.js
This is so that we can have github pages and the dev server work alongside.
Since github pages relies on the structure of the repo, whereas webpack-dev-server does not.
Fixes #253
> Redirect /dist/ assets to route

- README.md
This details that 15.5.4 was the last version of React tested to work with the Accessible Autocomplete (barring any documented issues) and versions 15.6.2 and 16.0 have received some basic testing.
> Update docs for React version

- webpack.config.babel.js
This redirects any requests for assets in dist/[subdirectory] correctly.
Fixes the issue of React and Preact examples not having their asset paths set correctly on local: http://localhost:8080/react/ and http://localhost:8080/preact/ would 404 for assets.
Related to: #254
Note: Duplicates https://github.com/alphagov/accessible-autocomplete/pull/264 that was closed by mistake.
> Fix asset paths for subdirectories

- test/integration/index.js
We are seeing the following intergration tests for the Accessible Autocomplete fail as they don't complete within the set time limit of 2000ms:
```
it('should announce status changes using two alternately updated aria live regions', () => {
if (isChrome) {
const flip = browser.$('div#ariaLiveA')
const flop = browser.$('div#ariaLiveB')
browser.click(input)
browser.setValue(input, 'a')
expect(flip.getText()).to.equal('')
expect(flop.getText()).to.equal('')
browser.waitUntil(() => { return flip.getText() !== '' },
liveRegionWaitTimeMillis,
'expected the first aria live region to be populated within ' + liveRegionWaitTimeMillis + ' milliseconds'
)
browser.addValue(input, 's')
browser.waitUntil(() => { return (flip.getText() === '' && flop.getText() !== '') },
liveRegionWaitTimeMillis, …
```
> Fix failing integration tests

- test/integration/index.js
Clearing the value doesn’t seem to work reliably when the autocomplete is currently open, especially if it has been interacted with (e.g. in a test that sends the arrow down key to focus on a result)
By sending ‘escape’ we dismiss any open autocompletes, which then seems to make the input-clearing work reliably.
> Dismiss open autocompletes between tests

- test/integration/index.js
The [wdio-sauce-service](https://github.com/webdriverio/webdriverio/tree/83dbe5d5c12fdb91b12db8c02cf2b8b50cfbd608/packages/wdio-sauce-service), which is responsible for reporting the build state back to Saucelabs, does not seem to take into account retries – we _believe_ that if a test fails, it will mark the build as failed in Saucelabs even if it is then retried and passes. This is confusing, as it does not match what we see in the Mocha reporter either locally or in the Travis build logs.
Using retries also masks situations where for example the autocomplete state is not reset correctly between tests, and thus the first attempt of a test always fails.
For these reasons, we're going to try removing retries and see what problems it causes (or, to look at another way, unmasks)
> Remove retries for functional tests

- CHANGELOG.md
- package-lock.json
- package.json
- [Pull request #388: Set aria-selected as a string instead of a boolean to avoid being dropped](https://github.com/alphagov/accessible-autocomplete/pull/388).
- [Pull request #400: Remove pointer events check](https://github.com/alphagov/accessible-autocomplete/pull/400).
- [Pull request #406: Make hint padding match input padding](https://github.com/alphagov/accessible-autocomplete/pull/406).
- [Pull request #407: Use a div element to wrap enhanced component](https://github.com/alphagov/accessible-autocomplete/pull/407).
- [Pull request #410: Fix long clicks not selecting options](https://github.com/alphagov/accessible-autocomplete/pull/410).
> Release version 2.0.2

- .travis.yml
- package.json
https://github.com/alphagov/accessible-autocomplete/pull/443 pinned the Sauce Connect Proxy for Travis. https://github.com/alphagov/accessible-autocomplete/pull/450 will update WebDriverIO to v6 so we no longer need to pin the version - the PR is currently blocked as we’re speaking to SauceLabs to see if we can enable the tests for IE9 with WebDriverIO v6.
This PR adds a temporary fix to unblock https://github.com/alphagov/accessible-autocomplete/pull/447. We can remove this in https://github.com/alphagov/accessible-autocomplete/pull/450.
> Pin Sauce Connect Proxy version to fix local tests

- CHANGELOG.md
- package-lock.json
- package.json
- [Pull request #415: Make React bundle work server-side in a NodeJS environment](https://github.com/alphagov/accessible-autocomplete/pull/415)
> Release version 2.0.3

- CONTRIBUTING.md
- Split command for pushing the tag onto a separate line to visually distinguish it from the multi-line command above it.
- Add steps for publishing a release on Github and announcing it.
> Improve docs for publishing a new version

- package-lock.json
- package.json
Bumps karma (test runner used for functional tests) and puppeteer, so that we can use a more modern version of Chromium.
This bumps the version of Chromium used for functional tests from 83 to 97.
> Bump version of Chromium used for functional tests

- README.md
Fixes [#561](https://github.com/alphagov/design-system-team-internal/issues/561).
This PR updates the README with links to the service manual recommendations on browsers and assistive tech.
> Add service manual links to README

- package-lock.json
This doesn't change the output of `npm run build`, but it does stop browserslist complaining at us.
> Update browserslist database

- README.md
**This change is cherry picked from #481 – I'm unable to force-push that branch to bring it up to date with changes in `main` because rebasing it introduces new GitHub workflows.**
---
The svg described in src/dropdown-arrow-down.js looks to be a triangle
> Change 'rectangle' for 'triangle' in the readme

- examples/index.html
Fixes [#161](https://github.com/alphagov/accessible-autocomplete/issues/161).
This PR replaces the microcopy 'Select your country' with 'Country', above our [autocomplete examples](https://alphagov.github.io/accessible-autocomplete/examples/).
We're making this change because, in a text input field, there would be nothing to 'select'.
Also, in a real service, this microcopy would be context-specific. So, it make sense to keep our own examples generic.
> Add generic microcopy to autocomplete examples

- package-lock.json
- package.json
- webpack.config.babel.js
This PR bumps all Webpack-replated dependencies to the latest versions compatible with webpack@4.
It makes no changes to the compiled output of the project, but should help close one or two security alerts.
Upgrading to Webpack v5 is currently blocked on `webpack-dev-server`. See #528 for more details.
> Bump Webpack to latest v4 version

- README.md
Fixes [#224](https://github.com/alphagov/accessible-autocomplete/issues/224) and [#436](https://github.com/alphagov/design-system-team-internal/issues/436).
This PR updates the autocomplete README with:
- a definition of the component
- advice to users about when not to use it
- a link to the country-picker README
- information about what support we can provide
- links to pinned support and research issues
> Link autocomplete READMEs and add info on support

- CHANGELOG.md
- package-lock.json
- package.json
- [Pull request #512: Make sure highlighted option is distinguishable in forced colors mode](https://github.com/alphagov/accessible-autocomplete/pull/512)
> Version 2.0.4

- .github/workflows/saucelabs.yaml
For reasons we don't yet understand, this step is sometimes getting stuck [^1] and never finishing, until either: 
- someone notices and cancels the workflow run
- it hits the default GitHub Actions timeout of 360 minutes (6 hours)
Either way, this is way longer than this job needs – when the tests run successfully they complete in around 2.5 minutes.
Reduce the timeout to 15 minutes for the job to avoid wasting resources, until we can solve the underlying issue with the workflow.
[^1]: Examples of builds getting 'stuck':
- https://github.com/alphagov/accessible-autocomplete/actions/runs/1922517196/attempts/1
- https://github.com/alphagov/accessible-autocomplete/actions/runs/1897972486/attempts/1
- https://github.com/alphagov/accessible-autocomplete/actions/runs/1894436033
> Add timeout for testing with SauceLabs

- .github/workflows/integration_tests.yaml
- .github/workflows/saucelabs.yaml
- .github/workflows/test.yaml
- .nvmrc
- CONTRIBUTING.md
Addresses deprecation warnings in GitHub Actions ahead of package updates
>[**Build & test**](https://github.com/alphagov/accessible-autocomplete/actions/runs/6904010579/job/18787315977)
>The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/setup-node@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
I've included an **.nvmrc** update ~to test things out but this might land in https://github.com/alphagov/accessible-autocomplete/pull/609 first~ cherry picked from https://github.com/alphagov/accessible-autocomplete/pull/609/commits/c7995df49c7644240378f2908675b7c6c80f1fb3
> Update GitHub Actions workflows with `.nvmrc`

- .github/dependabot.yml
- .github/workflows/test.yaml
This PR enables Dependabot updates for npm and GitHub Actions including:
1. Checks run at `monthly` intervals
2. Checks for unstaged changes after build
3. Grouped PRs for "build", "test" and "tooling" dependencies
Previously only security-related updates were included
~Probably wait for https://github.com/alphagov/accessible-autocomplete/pull/612 to merge first~
> Update all dependencies using Dependabot

- package.json
- test/karma.config.js
- webpack.config.mjs
This PR includes a few follow-up fixes to Karma + webpack
Previously `npm run karma` used webpack to overwrite `dist/` but using [`karma-webpack` defaults](https://github.com/codymikol/karma-webpack#default-webpack-configuration) instead. This has now been fixed so that Karma output is written to `os.tmpdir()` as the author intended
Karma webpack `devtool` option now [outputs inline source maps](https://www.npmjs.com/package/karma-webpack#source-maps) to fix warnings about missing source maps
We can now use the webpack CLI rather than the `webpack-dev-server` package binary:
```console
npx webpack
npx webpack serve
```
The [webpack `NoEmitOnErrorsPlugin` plugin](https://webpack.js.org/plugins/NoEmitOnErrorsPlugin/) is now enabled by default but we turn it off in development mode to help …
> Fix various Karma + webpack warnings and minor issues

- src/autocomplete.js
Fixes #434
I've used this as the base code for DLUHC. Needed to make small changes to get it to work with plotly dash so migrated from classes to hooks. This is one of the changes we've made to ensure lighthouse was 100.
PS: Happy to push the react hooks changes too if you are interested.
> ariaActivedescendant = false not valid aria

- CHANGELOG.md
I _think_ I collected all the revelant [pull requests merged since the last release](https://github.com/alphagov/accessible-autocomplete/pulls?q=is%3Apr+sort%3Aupdated-desc+-author%3Aapp%2Fdependabot+is%3Amerged+merged%3A%3E2022-02-07).
Closes #624.
> Update list of changes since last release in the CHANGELOG

- README.md
#677 (not to be merged) provides the branch testing against Preact 10.19.6, which showed a single automated test failing in IE11.
This commits adds a notice to the README to clarify which versions of Preact were tested and the result, in a similar fashion to the section for React.
Closes #667
> Add notice about supported Preact versions in README

- README.md
Update the notice about React versions in the README with the results of:
- #681 
- #682 
- #683 
Tests didn't show any issue (accounting for React 18 dropping support for IE, meaning the tests fail for that branch), though it's only automated testing and some (very) light manual testing so we keep encouraging people to carry their own testing.
Closes #668
> Update notice about supported React versions in README 

- .github/dependabot.yml
@romaricpascal sums it up well in [his comment](https://github.com/alphagov/accessible-autocomplete/pull/719#issuecomment-2277510897) on https://github.com/alphagov/accessible-autocomplete/pull/719
> Remove preact from dependabot build group

- CHANGELOG.md
- package-lock.json
- package.json
- [Pull request #727: Add `aria-controls` to aria props](https://github.com/alphagov/accessible-autocomplete/pull/727)
- [Pull request #724: Add accessibility controls to 'No results' list item](https://github.com/alphagov/accessible-autocomplete/pull/724)
- [Pull request #729: Move `aria-labelledby` into computed menu props](https://github.com/alphagov/accessible-autocomplete/pull/729)
> Release v3.0.1

- netlify.toml
What it says on the tin. Adds a netlify.toml that only contains the redirect from "/" to "/examples". Used only for netlify previews right now so that folks not in the know aren't wondering why the root of the preview doesn't show anything.
> Add automatic redirects to examples for netlify previews
