alphagov/accessible-autocomplete

CHANGELOG.md, src/typeahead.jsx
This should help people rewrite their selection more easily.
cc @edwardhorsford
=> Select entire text region when focusing into the input

CHANGELOG.md, examples/styled.css, src/typeahead.jsx, test/browser/index.jsx
I've done some fixes for a variety of browser and assistive technology combinations.
Commits have info about every individual fix.
=> Accessibility hardening

src/typeahead.jsx, test/browser/index.jsx
Setting them in render isn't sufficient.
=> Refactor defaultProps

CHANGELOG.md, src/typeahead.jsx
This makes it work better with Dragon NaturallySpeaking.
=> Poll the input element to pick up `.value` changes

CHANGELOG.md, README.md, examples/styled.css, examples/styled.html, src/status.jsx, src/typeahead.jsx, src/wrapper.jsx, test/browser/index.jsx
Set to true to highlight the first option when the user types in something and receives results. Pressing enter will select it.
=> Add autoselect prop

examples/styled.css, src/typeahead.jsx
=> Add hinting

CHANGELOG.md, README.md, examples/index.html, src/typeahead.jsx, src/wrapper.jsx
These allow users to override how the suggestions are displayed.
The first 3 commits in this PR are not part of this work.
=> Add templating options

examples/index.html
Should make them easier to skim.
=> Update examples page with better headings

CHANGELOG.md, README.md, examples/index.html, src/typeahead.jsx, src/wrapper.jsx
This option will populate the placeholder attribute on the input element.
=> Add the `placeholder` option

CHANGELOG.md, README.md, examples/index.html, src/wrapper.jsx
Document how to do it in the README instead.
=> Don't prepopulate defaultValue in enhanceSelectElement

CHANGELOG.md, README.md, examples/index.html, src/typeahead.jsx, src/wrapper.jsx
This allows users to disable this behaviour.
=> Add `showNoOptionsFound` property

examples/index.html
There's some content work to do for this page as at the moment it's a bit cryptic but this PR makes the current docs easier to read.
=> Update example page styles so it's easier to read

README.md, accessibility-criteria.md
Fix a heading and use bullets in accessibility criteria for easier referencing.
=> Doc updates

accessibility-criteria.md
The number of matches is optional.
Closes #65.
=> Update accessibility criterion 8

README.md
Closes #41.
@adamsilver what do you think of this?
=> Update readme to discourage use of `placeholder`

examples/form.html, examples/index.html
This demonstrates end to end use in a real form with multiple `name`s.
Closes #42.
=> Add form example

package.json, test/karma.conf.js, webpack.config.babel.js, yarn.lock
=> Update to webpack 2

README.md
=> Add analytics intro and onSelect example

CHANGELOG.md, README.md, examples/index.html, src/wrapper.js, test/functional/wrapper.js, webpack.config.babel.js
Previously https://github.com/alphagov/accessible-typeahead/pull/50.
=> Write tests for wrapper

src/status.js
=> Fix status region readability

README.md
- Clarify usage with and without module systems
- Clarify basic usage with a container `<div>`
Closes #144.
=> Update usage section in README

README.md
=> Fix script src in README

CHANGELOG.md, package-lock.json, package.json
- Allow space to confirm an option, fixes #98.
- Add support for navigating lists on IE9, 10 and 11, fixes #193.
=> 1.4.2 - 2017-07-18

CHANGELOG.md, CONTRIBUTING.md, package-lock.json, package.json
- [Feature] Add ability to translate texts. Relates to #96. By [@sventschui](https://github.com/sventschui).
=> 1.5.0 - 2017-07-18

examples/form.html
Noticed the labels weren't being announced.
=> Fixed label association

examples/form.html
#208 broke the example; should have tested the change locally before submitting… apologies.
=> Fixed form example

package-lock.json, package.json
https://github.com/mysticatea/npm-run-all/releases/v4.1.5
=> Bump npm-run-all to avoid potential vulnerability locally

README.md
Little change that means people get to the right place first time.
=> Fix readme pointing to travis-ci.org

CHANGELOG.md
This updates the changelog to include the edited version of the v2.0.0 (unreleased) release note.
=> Add edited v2.0.0 (unreleased) changelog

README.md
Update README to explain that we cannot currently respond to issues or pull requests.
=> Update support status

.travis.yml
=> Fix Travis CI config to de-duplicate addons key

CHANGELOG.md, CONTRIBUTING.md
=> Update references to master branch

CONTRIBUTING.md
Part of https://github.com/alphagov/design-system-team-internal/issues/618
=> Update references to cred store

accessibility-criteria.md
Adds [minor WCAG 2.2 guidance](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit#bookmark=id.rj60zcomcwen) into the accessibility acceptance criteria.
=> Update accessibility criteria for WCAG 2.2
